SoSheWrote/config/routes.rb
Rails.application.routes.draw do
  
  post 'sessions/create'

  post 'sessions/destroy'

  resources :tags
  resources :categories
  resources :articles do
    resources :comments
  end
  
  get "/login", to: 'sessions#new', as: "login"
  get "/bio", to: 'publics#bio', as: 'bio'
  get "/post/:id", to: 'posts#show', as: "post"
  get "/:category(/:tag)", to: 'posts#index', as: "posts"
  
  
  root 'publics#index'
end

SoSheWrote/app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :category, inverse_of: :articles
  has_many :comments
  has_many :article_tags
  has_many :tags, through: :article_tags
  
  accepts_nested_attributes_for :article_tags, :tags, :category
  validates_presence_of :category
  validates :content, presence: true
  validates :title, presence: true, uniqueness: true
  
  def self.is_published?
    where(published: true)
  end
  
end

SoSheWrote/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  
  http_basic_authenticate_with :name => "alyssa", :password => "secret", :except => [:index, :show]

  def index
    @articles = Article.all
    @tags = Tag.all
    @categories = Category.all
    
    if params[:category]
      @articles = Article.where(category: params[:category.name])
    else
      @articles = Article.all
    end
    
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def edit
    
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    Rails.logger.info ":::PARAMS:::"
    Rails.logger.info params
    Rails.logger.info "::::::::"
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      set_published_at
      params.require(:article).permit(:title, :content, :category_id, :published)
    end
    
    def set_published_at
      if params[:article][:published] == "1" and @article.published == false
        @article.published_at = Time.now
      end
    end
end

SoSheWrote/app/helpers/articles_helper.rb
module ArticlesHelper
end

SoSheWrote/app/views/articles/_category.erb
<%= f.hidden_field :category_id, value: "#{@article.category_id}" %>
<% count = 1 %>
	

SoSheWrote/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "New Article Title" %><br>
    <%= f.text_field :title %>
  </div>
	<div class="field">
		<%= f.label :content%>
		<%= tinymce %>
		<%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 100 %>
	</div>
		
		<div class="field">
			<%= f.label :category %>
			<%= f.collection_select(:category_id, Category.all, :id, :name, {multiple: false}) %>
		</div>
		<div class="field">
			<%= f.check_box :published %>
			<%= f.label :published %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
<% end %>

SoSheWrote/app/views/articles/_tags.erb
<%= f.hidden_field :article_tags, value: "#{@article.tags}" %>
<% count = 1 %>
	<div class="field">
		<%= f.label :tags %>
		<%= f.collection_check_boxes(:tags, Tag.all, :id, :name, {:multiple => true}) %>
		<p>Or add new tag: </p>
		<%= f.text_field :tags %>
	</div>

SoSheWrote/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

SoSheWrote/app/views/articles/index.html.erb
<% if admin? %>

<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= raw article.content.truncate(300) %></td>
        <td><%= article.category.name if article.category.present? %></td>
				<td>
					<%= article.published ? article.published_at : article.published %>
				</td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="entry-title"><%= link_to 'New Article', new_article_path %></div>

<% end %>

SoSheWrote/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

SoSheWrote/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div>Title:</div>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= raw @article.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @article.category.name if @article.category.present? %>
</p>

<p>
	<strong>Tags:</strong>
	<% @article.tags.each do |tag| %>
		<%= tag.name %>
	<% end %>
</p>

<p>
  <strong>Published:</strong>
  <%= @article.published %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<br>

<p>
	<strong>Comments:</strong>
</p>

	<% @article.comments.all.each do |comment| %>
	
	<div>Title: <%= comment.title %></div>
	<div>Author: <%= comment.author %></div>
	<div>Content: <%= comment.content %></div>
  <div><%= link_to 'Show', article_comments_path(comment) %></div>
  <div><%= link_to 'Destroy', article_comments_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></div>
<br>
<% end %>