SoSheWrote/config/routes.rb
Rails.application.routes.draw do
  
  post 'sessions/create'

  post 'sessions/destroy'

  resources :tags
  resources :categories
  resources :articles do
    resources :comments
  end
  
  get "/login", to: 'sessions#new', as: "login"
  get "/bio", to: 'publics#bio', as: 'bio'
  get "/post/:id", to: 'posts#show', as: "post"
  get "/:category(/:tag)", to: 'posts#index', as: "posts"
  
  
  root 'publics#index'
end

SoSheWrote/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
  validates :author, presence: true
  validates :content, presence: true

end

SoSheWrote/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.article_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_path(id: @comment.article), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(id: @comment.article), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :content, :title, :article_id)
    end
end

SoSheWrote/app/helpers/comments_helper.rb
module CommentsHelper
end

SoSheWrote/app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
<div class="main-text-container">
	<div class="entry-title"><%= comment.title %></div>
	<div class="entry-date">Posted: <%= comment.created_at.strftime('%a. %B %d, %Y') %>  </div>
	<div class="entry-date"> By: <%= comment.author %></div>
	<p class="main-content"><%= comment.content %></p>
</div>
<% end %>
<br>

SoSheWrote/app/views/comments/_form.html.erb
<%= form_for([@post, @comment], url: article_comments_path(article_id: @post.id)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SoSheWrote/app/views/comments/_new.html.erb
<div class="entry-title">New Comment</div>

<p class="main-content">

<%= render 'comments/form' %>

</p>

SoSheWrote/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

SoSheWrote/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th>Atricle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.content %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', article_comments_path %></td>
        <td><%= link_to 'Destroy', article_comments_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Article', articles_path %>
<%= link_to 'New Comment', new_article_comment_path %>

SoSheWrote/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Atricle:</strong>
  <%= @comment.article %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>